title: Adventures in Marine Ecology
author: chelsie12
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Working in understand species distributions and interactions within marine ecosystems has taken me to the rocky intertidal, flying in small airplanes, and SCUBA diving across the Pacific Remote Islands.
# social links
twitter_username: CWCounsell

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
